### ISSUE TITLE
NotImplementedError: Unknown task state: canceling

### ISSUE THREAD

**Issue by dkliban** [pulp/pulp-cli#329]
```
$ pulp task cancel --href /pulp/api/v3/tasks/86d46871-0f52-411f-b3ed-8a6dc52ea2e1/
Waiting to cancel task /pulp/api/v3/tasks/86d46871-0f52-411f-b3ed-8a6dc52ea2e1/
.Traceback (most recent call last):
  File "/usr/local/lib/pulp/bin/pulp", line 33, in <module>
    sys.exit(load_entry_point('pulp-cli', 'console_scripts', 'pulp')())
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/devel/pulp-cli/pulpcore/cli/core/task.py", line 53, in cancel
    raise e
  File "/home/vagrant/devel/pulp-cli/pulpcore/cli/core/task.py", line 50, in cancel
    pulp_ctx.wait_for_task(entity)
  File "/home/vagrant/devel/pulp-cli/pulpcore/cli/common/context.py", line 191, in wait_for_task
    raise NotImplementedError(f"Unknown task state: {task['state']}")
NotImplementedError: Unknown task state: canceling
```

**Comment by dkliban** [comment]
I was using 0.9. I'll close the issue.
