### ISSUE TITLE
CLI doesn't wait for very long tasks?

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulp-cli#433]
## Summary
If I have a task that takes a really long time, it seems that the CLI doesn't continue waiting. Could that be the case?

## Steps to reproduce
I was using these commands:
```
#!/bin/bash

set -ev

repo_name="repo$RANDOM"
remote_name="remote$RANDOM"
url="https://fixtures.pulpproject.org/file/PULP_MANIFEST"

pulp file remote create --name $remote_name --url $url
pulp file repository create --name $repo_name --remote $remote_name
pulp file repository sync --name $repo_name

repo_name="repo$RANDOM"
remote_name="remote$RANDOM"

pulp file remote create --name $remote_name --url $url
pulp file repository create --name $repo_name --remote $remote_name
pulp file repository sync --name $repo_name
```

Also I was debugging the task code so for the purposes of reproducing, you can introduce a really long sleep statement in the pulp_file task sync code. Then you'll see a line like this:

```
pulp file repository sync --name $repo_name
Started background task /pulp/api/v3/tasks/a980d50b-2916-4cd7-8605-22eb29dc3067/
........................................................................................................................
```

What is strange is that the CLI will eventually just go on to execute more statements in the script. This seems incorrect.

## Expected behavior
The CLI to wait indefinitely until a task is either finished, errored, or cancelled.

## Pulp and pulp-cli version info
`pulp3 command line interface, version 0.10.0.dev0`

```
{"versions": [{"component": "core", "version": "3.17.0.dev"}, {"component": "file", "version": "1.11.0.dev"}, {"component": "certguard", "version": "1.6.0.dev"}], "online_workers": [{"pulp_created": "2021-11-23T17:04:32.002545Z", "pulp_href": "/pulp/api/v3/workers/ba010ff5-a4d1-4c17-ba80-1e4986000a2c/", "name": "208541@pulp3-source-fedora34.fedora.example.com", "last_heartbeat": "2021-11-23T17:13:28.589681Z"}, {"pulp_created": "2021-11-23T17:04:31.797085Z", "pulp_href": "/pulp/api/v3/workers/6a0ae84d-c95f-4174-838c-e708f2b72923/", "name": "208540@pulp3-source-fedora34.fedora.example.com", "last_heartbeat": "2021-11-23T17:13:28.592263Z"}], "online_content_apps": [{"name": "208550@pulp3-source-fedora34.fedora.example.com", "last_heartbeat": "2021-11-23T17:13:22.569405Z"}, {"name": "208548@pulp3-source-fedora34.fedora.example.com", "last_heartbeat": "2021-11-23T17:13:22.571535Z"}, {"name": "208546@pulp3-source-fedora34.fedora.example.com", "last_heartbeat": "2021-11-23T17:13:22.572287Z"}, {"name": "208547@pulp3-source-fedora34.fedora.example.com", "last_heartbeat": "2021-11-23T17:13:22.573367Z"}, {"name": "208543@pulp3-source-fedora34.fedora.example.com", "last_heartbeat": "2021-11-23T17:13:22.574677Z"}, {"name": "208545@pulp3-source-fedora34.fedora.example.com", "last_heartbeat": "2021-11-23T17:13:22.574656Z"}, {"name": "208549@pulp3-source-fedora34.fedora.example.com", "last_heartbeat": "2021-11-23T17:13:22.575010Z"}, {"name": "208551@pulp3-source-fedora34.fedora.example.com", "last_heartbeat": "2021-11-23T17:13:22.575911Z"}], "database_connection": {"connected": true}, "redis_connection": {"connected": true}, "storage": {"total": 42006183936, "used": 3754827776, "free": 36087148544}}
```

**Comment by mdellweg** [comment]
I think, this is fixed here: https://github.com/pulp/pulp-cli/pull/258
Can you verify it still happens using the 0.10.0 release?

**Comment by bmbouter** [comment]
I tried upgrading to that, but now I get:

```
pulp file remote create --name $remote_name --url $url
Traceback (most recent call last):
  File "/usr/local/lib/pulp/bin/pulp", line 33, in <module>
    sys.exit(load_entry_point('pulp-cli', 'console_scripts', 'pulp')())
  File "/usr/local/lib/pulp/bin/pulp", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/vagrant/devel/pulp-cli/pulpcore/cli/common/__init__.py", line 102, in <module>
    def main(
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/click/decorators.py", line 304, in decorator
    return option(*(param_decls or ("--version",)), **attrs)(f)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/click/decorators.py", line 192, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/click/core.py", line 1714, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'package_name'
```

**Comment by bmbouter** [comment]
Actually my problem was environmental. I reinstalled pulp-cli and I can confirm this is resolved for me. Wow my pulp-cli was really old. Thanks!
