### ISSUE TITLE
error Could not find style module 'solarized-dark'.

### ISSUE THREAD

**Issue by lbluenote** [pulp/pulp-cli#477]
## Summary
pygments.util.ClassNotFound: Could not find style module 'solarized-dark' error on Ubuntu 20.04

## Steps to reproduce
pulp status

## Stacktrace/Error log
pulp status
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pygments/styles/__init__.py", line 64, in get_style_by_name
    mod = __import__('pygments.styles.' + mod, None, None, [cls])
ModuleNotFoundError: No module named 'pygments.styles.solarized-dark'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./pulp", line 8, in <module>
    sys.exit(main())
  File "/home/luca/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/luca/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/luca/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/luca/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/luca/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/luca/.local/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/luca/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/luca/.local/lib/python3.8/site-packages/pulpcore/cli/core/status.py", line 45, in status
    pulp_ctx.output_result(result)
  File "/home/luca/.local/lib/python3.8/site-packages/pulpcore/cli/common/context.py", line 113, in output_result
    output = highlight(output, JsonLexer(), Terminal256Formatter(style=PYGMENTS_STYLE))
  File "/usr/lib/python3/dist-packages/pygments/formatters/terminal256.py", line 124, in __init__
    Formatter.__init__(self, **options)
  File "/usr/lib/python3/dist-packages/pygments/formatter.py", line 67, in __init__
    self.style = _lookup_style(options.get('style', 'default'))
  File "/usr/lib/python3/dist-packages/pygments/formatter.py", line 22, in _lookup_style
    return get_style_by_name(style)
  File "/usr/lib/python3/dist-packages/pygments/styles/__init__.py", line 66, in get_style_by_name
    raise ClassNotFound("Could not find style module %r" % mod +
pygments.util.ClassNotFound: Could not find style module 'solarized-dark'.

## Pulp and pulp-cli version info
pulp3 command line interface, version 0.13.0

**Comment by lbluenote** [comment]
need to update to Pygments module to the latest version
pip3 install -U Pygments

**Comment by mdellweg** [comment]
Did that solve the problem? I would recommend running the cli in a virtualenv.
