### ISSUE TITLE
--retain-repo-versions 1 causes "KeyError: 'repositories_partial_update'"

### ISSUE THREAD

**Issue by abotelho-cbn** [pulp/pulp-cli#529]
`pulp1:~ # pulp status
{
  "versions": [
    {
      "component": "core",
      "version": "3.19.0"
    },
    {
      "component": "rpm",
      "version": "3.17.5"
    },
    {
      "component": "python",
      "version": "3.6.0"
    },
    {
      "component": "maven",
      "version": "0.3.2"
    },
    {
      "component": "file",
      "version": "1.10.2"
    },
    {
      "component": "deb",
      "version": "2.18.0"
    },
    {
      "component": "container",
      "version": "2.12.1"
    },
    {
      "component": "certguard",
      "version": "1.5.2"
    },
    {
      "component": "ansible",
      "version": "0.13.0"
    }
  ],
  "online_workers": [
    {
      "pulp_href": "/pulp/api/v3/workers/ca711299-1972-48b6-a2bb-67dc8b34a178/",
      "pulp_created": "2022-06-14T22:32:42.226535Z",
      "name": "15412@ef994fae625f",
      "last_heartbeat": "2022-07-14T17:06:51.355585Z",
      "current_task": null
    },
    {
      "pulp_href": "/pulp/api/v3/workers/a4487e9d-df4f-46ed-b67c-bd84a49ee201/",
      "pulp_created": "2022-06-14T22:32:40.944313Z",
      "name": "15409@ef994fae625f",
      "last_heartbeat": "2022-07-14T17:07:01.292294Z",
      "current_task": null
    }
  ],
  "online_content_apps": [
    {
      "name": "15469@ef994fae625f",
      "last_heartbeat": "2022-07-14T17:06:55.821491Z"
    },
    {
      "name": "15468@ef994fae625f",
      "last_heartbeat": "2022-07-14T17:06:59.581073Z"
    }
  ],
  "database_connection": {
    "connected": true
  },
  "redis_connection": {
    "connected": false
  },
  "storage": {
    "total": 660019150848,
    "used": 180677230592,
    "free": 451386941440
  }
}
`

`pulp1:~ # pulp shell
Starting Pulp3 interactive shell...
pulp> deb repository update --name debian12 --retain-repo-versions 1 
KeyError: 'repositories_partial_update'`

`pulp1:~ # pulp deb repository update --name debian12 --retain-repo-versions 1
Traceback (most recent call last):
  File "/usr/bin/pulp", line 11, in <module>
    load_entry_point('pulp-cli==0.14.0', 'console_scripts', 'pulp')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/pulpcore/cli/common/generic.py", line 50, in invoke
    return super().invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pulpcore/cli/common/generic.py", line 802, in callback
    entity_ctx.update(href=entity_ctx.pulp_href, body=body)
  File "/usr/lib/python3.8/site-packages/pulpcore/cli/common/context.py", line 525, in update
    return self.call(
  File "/usr/lib/python3.8/site-packages/pulpcore/cli/common/context.py", line 431, in call
    return self.pulp_ctx.call(
  File "/usr/lib/python3.8/site-packages/pulpcore/cli/common/context.py", line 148, in call
    result = self.api.call(operation_id, parameters=parameters, body=body, uploads=uploads)
  File "/usr/lib/python3.8/site-packages/pulpcore/cli/common/openapi.py", line 239, in call
    method, path = self.operations[operation_id]
KeyError: 'repositories_partial_update'`

API works:
`curl --request PUT \
  --url https://example.com/pulp/api/v3/repositories/deb/apt/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/ \
  --header 'Authorization: Basic <token>' \
  --header 'Content-Type: application/json' \
  --data '{
	"name": "debian12",
	"retain_repo_versions": 1
}'`

**Comment by mdellweg** [comment]
In the meantime, you can probably install pulp-cli 0.13 to make it work again.

**Comment by mdellweg** [comment]
0.14.1 is released
