### ISSUE TITLE
pulp task cancel --all failing with assertion error

### ISSUE THREAD

**Issue by ggainey** [pulp/pulp-cli#561]
## Summary
`pulp task cancel --all` fails with 
```
 File "/home/vagrant/devel/pulp-cli/pulpcore/cli/common/openapi.py", line 157, in extract_params
    assert isinstance(param, Iterable) and not isinstance(param, str)
AssertionError
```

## Steps to reproduce
- Stand up pulp-cli from current-main.
- Execute `pulp task cancel --all`

## Expected behavior
Stop being so assertive.

## Stacktrace/Error log

```
Traceback (most recent call last):
  File "/usr/local/lib/pulp/bin/pulp", line 8, in <module>
    sys.exit(main())
  File "/home/vagrant/devel/pulp-cli/pulp_cli/__init__.py", line 32, in main
    return _main()
  File "/usr/local/lib/pulp/lib64/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/pulp/lib64/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/devel/pulp-cli/pulpcore/cli/common/generic.py", line 84, in invoke
    return super().invoke(ctx)
  File "/usr/local/lib/pulp/lib64/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/devel/pulp-cli/pulpcore/cli/common/generic.py", line 84, in invoke
    return super().invoke(ctx)
  File "/usr/local/lib/pulp/lib64/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/devel/pulp-cli/pulpcore/cli/common/generic.py", line 84, in invoke
    return super().invoke(ctx)
  File "/usr/local/lib/pulp/lib64/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/pulp/lib64/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/pulp/lib64/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/pulp/lib64/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/pulp/lib64/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/pulp/lib64/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/vagrant/devel/pulp-cli/pulpcore/cli/core/task.py", line 109, in cancel
    tasks = task_ctx.list(limit=1 << 64, offset=0, parameters={"state__in": ",".join(states)})
  File "/home/vagrant/devel/pulp-cli/pulpcore/cli/common/context.py", line 527, in list
    result: Dict[str, Any] = self.call("list", parameters=payload)
  File "/home/vagrant/devel/pulp-cli/pulpcore/cli/common/context.py", line 479, in call
    return self.pulp_ctx.call(
  File "/home/vagrant/devel/pulp-cli/pulpcore/cli/common/context.py", line 175, in call
    result = self.api.call(
  File "/home/vagrant/devel/pulp-cli/pulpcore/cli/common/openapi.py", line 318, in call
    query_params = self.extract_params("query", path_spec, method_spec, parameters)
  File "/home/vagrant/devel/pulp-cli/pulpcore/cli/common/openapi.py", line 157, in extract_params
    assert isinstance(param, Iterable) and not isinstance(param, str)
AssertionError
```
## Pulp and pulp-cli version info

```
(pulp) [vagrant@pulp3-source-fedora36 pulp-cli]$ pulp --version
pulp3 command line interface, version 0.16.0.dev0
(pulp) [vagrant@pulp3-source-fedora36 pulp-cli]$ pulp status
{
  "versions": [
    {
      "component": "core",
      "version": "3.22.0.dev",
      "package": "pulpcore"
    },
    {
      "component": "rpm",
      "version": "3.19.0.dev",
      "package": "pulp-rpm"
    },
    {
      "component": "file",
      "version": "1.12.0.dev",
      "package": "pulp-file"
    },
    {
      "component": "certguard",
      "version": "1.6.0.dev",
      "package": "pulp-certguard"
    }
  ],
  "online_workers": [
    {
      "pulp_href": "/pulp/api/v3/workers/518a933b-5c25-4e93-81ef-9ff8e56b9310/",
      "pulp_created": "2022-10-07T15:41:45.170875Z",
      "name": "114587@pulp3-source-fedora36.padre-fedora.example.com",
      "last_heartbeat": "2022-10-07T18:15:58.009612Z",
      "current_task": null
    },
    {
      "pulp_href": "/pulp/api/v3/workers/b9076e54-2af7-40db-899a-ce4d9a1d2115/",
      "pulp_created": "2022-10-07T15:41:50.297191Z",
      "name": "114652@pulp3-source-fedora36.padre-fedora.example.com",
      "last_heartbeat": "2022-10-07T18:15:58.199158Z",
      "current_task": null
    },
    {
      "pulp_href": "/pulp/api/v3/workers/60dbfa6c-59b0-4189-9bb7-1cac8e5db6f7/",
      "pulp_created": "2022-10-07T15:41:50.541628Z",
      "name": "114661@pulp3-source-fedora36.padre-fedora.example.com",
      "last_heartbeat": "2022-10-07T18:15:58.288200Z",
      "current_task": null
    },
    {
      "pulp_href": "/pulp/api/v3/workers/a9223280-b280-4391-ad42-a0a8602eb620/",
      "pulp_created": "2022-10-07T15:41:45.250628Z",
      "name": "114588@pulp3-source-fedora36.padre-fedora.example.com",
      "last_heartbeat": "2022-10-07T18:15:58.289249Z",
      "current_task": null
    },
    {
      "pulp_href": "/pulp/api/v3/workers/2af997d9-9517-4b7c-81bd-46d707eca780/",
      "pulp_created": "2022-10-07T15:41:50.584997Z",
      "name": "114648@pulp3-source-fedora36.padre-fedora.example.com",
      "last_heartbeat": "2022-10-07T18:15:58.293417Z",
      "current_task": null
    },
    {
      "pulp_href": "/pulp/api/v3/workers/7ab98208-361b-45c3-b0f1-8b40b004295f/",
      "pulp_created": "2022-10-07T15:41:50.508569Z",
      "name": "114665@pulp3-source-fedora36.padre-fedora.example.com",
      "last_heartbeat": "2022-10-07T18:15:58.293618Z",
      "current_task": null
    },
    {
      "pulp_href": "/pulp/api/v3/workers/f93b403e-6173-4052-b4b6-86c528d064d6/",
      "pulp_created": "2022-10-07T15:41:50.565763Z",
      "name": "114657@pulp3-source-fedora36.padre-fedora.example.com",
      "last_heartbeat": "2022-10-07T18:15:58.293841Z",
      "current_task": null
    },
    {
      "pulp_href": "/pulp/api/v3/workers/713b6272-8b5d-49d6-bafb-30d795dc57ec/",
      "pulp_created": "2022-10-07T15:41:50.572314Z",
      "name": "114644@pulp3-source-fedora36.padre-fedora.example.com",
      "last_heartbeat": "2022-10-07T18:15:58.360755Z",
      "current_task": null
    }
  ],
  "online_content_apps": [
    {
      "name": "114591@pulp3-source-fedora36.padre-fedora.example.com",
      "last_heartbeat": "2022-10-07T18:15:55.235695Z"
    },
    {
      "name": "114594@pulp3-source-fedora36.padre-fedora.example.com",
      "last_heartbeat": "2022-10-07T18:15:55.290156Z"
    },
    {
      "name": "114593@pulp3-source-fedora36.padre-fedora.example.com",
      "last_heartbeat": "2022-10-07T18:15:55.353227Z"
    },
    {
      "name": "114597@pulp3-source-fedora36.padre-fedora.example.com",
      "last_heartbeat": "2022-10-07T18:15:55.411816Z"
    },
    {
      "name": "114592@pulp3-source-fedora36.padre-fedora.example.com",
      "last_heartbeat": "2022-10-07T18:15:55.453636Z"
    },
    {
      "name": "114590@pulp3-source-fedora36.padre-fedora.example.com",
      "last_heartbeat": "2022-10-07T18:15:55.503374Z"
    },
    {
      "name": "114595@pulp3-source-fedora36.padre-fedora.example.com",
      "last_heartbeat": "2022-10-07T18:15:55.535146Z"
    },
    {
      "name": "114596@pulp3-source-fedora36.padre-fedora.example.com",
      "last_heartbeat": "2022-10-07T18:15:55.537025Z"
    }
  ],
  "database_connection": {
    "connected": true
  },
  "redis_connection": {
    "connected": true
  },
  "storage": {
    "total": 42863669248,
    "used": 2823503872,
    "free": 39208353792
  },
  "content_settings": {
    "content_origin": "http://pulp3-source-fedora36.padre-fedora.example.com",
    "content_path_prefix": "/pulp/content/"
  }
}
```
## Additional context
Works fine in 0.15.0.

**Comment by mdellweg** [comment]
Can you append `, f"Parameter '{name}' is supposed to be a list."` to the `assert` line?
I am pretty sure this is a fallout of the recently added validation #555 .
